name: 'Sifflet dbt impact analysis action'
description: 'When you raise a PR containing dbt updates, this action adds an impact analysis report using the Sifflet API.'
inputs:
  git-provider-token:
    required: true
  sifflet-instance-url:
    required: true
  sifflet-api-token:
    required: true
  impacted-asset-types:
    required: false
    default: ''
  impacted-tags:
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'docker://public.ecr.aws/t4w7y9m8/sifflet/dbt-impact-analysis:v1.0.0'
  args:
    - 'github'
    - ${{ inputs.git-provider-token }}
    - ${{ inputs.sifflet-instance-url }}
    - ${{ inputs.sifflet-api-token }}
    - ${{ inputs.impacted-asset-types }}
    - ${{ inputs.impacted-tags }}
